services:
  web:
    build:
      target: web
      context: .
    command: "./backend/start.sh"
    environment:
      - MONGO_DATABASE_URI=mongodb://admin:secret@mongodb:27017
      - DOCKER_ENV=0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/home/docker/code
    depends_on:
      - mongo
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
volumes:
  mongo-data:
  rabbitmq_data:
